FISCO-BCOS/bcos-framework

interfaces/crypto/CommonType.h, interfaces/ledger/LedgerInterface.h, interfaces/ledger/ledgerInterface.h, interfaces/protocol/Block.h, interfaces/protocol/BlockHeader.h, interfaces/protocol/ProtocolTypeDef.h, interfaces/protocol/Transaction.h, interfaces/protocol/TransactionReceipt.h, interfaces/storage/Common.h, interfaces/storage/StorageInterface.h, libutilities/Error.h
=> update include path

interfaces/protocol/BlockFactory.h, interfaces/protocol/BlockHeaderFactory.h, interfaces/protocol/TransactionFactory.h, interfaces/protocol/TransactionReceiptFactory.h, interfaces/protocol/TransactionSubmitResult.h
=> update protocol's include dir

interfaces/protocol/Block.h, interfaces/protocol/Transaction.h, libprotocol/protobuf/PBBlock.h, test/unittests/libprotocol/FakeBlock.h, test/unittests/libprotocol/FakeTransaction.h, test/unittests/libprotocol/FakeTransactionReceipt.h, test/unittests/libprotocol/PBBlockTest.cpp
remove list methods from Block
=> remove list methods from Block

.github/workflows/workflow.yml, CMakeLists.txt, interfaces/crypto/CommonType.h, interfaces/crypto/KeyInterface.h, interfaces/crypto/Signature.h, interfaces/protocol/BlockHeader.h, interfaces/protocol/Protocol.h, interfaces/protocol/ProtocolTypeDef.h, interfaces/protocol/Transaction.h, libcodec/scale/ScaleDecoderStream.h, libcodec/scale/ScaleEncoderStream.h, libprotocol/protobuf/PBBlockHeader.cpp, libprotocol/protobuf/PBBlockHeader.h, libprotocol/protobuf/PBTransaction.h, test/CMakeLists.txt, test/unittests/libprotocol/FakeBlockHeader.h, test/unittests/libprotocol/PBBlockHeaderTest.cpp
Update BlockHeader class member, use gsl::span insted of std::vector
=> Update BlockHeader class member

interfaces/crypto/CryptoSuite.h, interfaces/crypto/Hash.h, interfaces/crypto/KeyInterface.h, interfaces/crypto/KeyPairInterface.h, interfaces/crypto/Signature.h, interfaces/crypto/SymmetricEncryption.h
=> add ../../ for include path

interfaces/protocol/BlockHeader.h, libprotocol/protobuf/PBBlockHeader.cpp, libprotocol/protobuf/PBBlockHeader.h
add const& for BlockHeader::hash()
=> add const& for BlockHeader::hash()

libprotocol/Common.h, libprotocol/Exceptions.h, libprotocol/LogEntry.h, libprotocol/ParallelMerkleProof.h, libprotocol/TransactionSubmitResultImpl.h
=> add ../ for header

interfaces/protocol/Transaction.h, test/unittests/libprotocol/PBTransactionTest.cpp
=> add exception for verify

CMakeLists.txt, cmake/InstallInclude.cmake, interfaces/consensus/ConsensusInterface.h, interfaces/ledger/LedgerInterface.h, interfaces/protocol/Block.h, interfaces/protocol/BlockFactory.h, interfaces/protocol/Transaction.h, interfaces/sealer/SealerInterface.h, interfaces/txpool/TxPoolInterface.h, libprotocol/protobuf/PBBlockFactory.h, libprotocol/protobuf/PBTransaction.cpp, libprotocol/protobuf/PBTransaction.h, libsealer/CMakeLists.txt, libsealer/Common.h, libsealer/Sealer.cpp, libsealer/Sealer.h, libsealer/SealerConfig.h, libsealer/SealingManager.cpp, libsealer/SealingManager.h
1. add basic implementation of Sealer
2. update asyncSealTxs, add asyncMarkTxs to mark the sealed txs
=> add basic implementation of Sealer

interfaces/consensus/ConsensusTypeDef.h, interfaces/front/FrontServiceInterface.h, interfaces/gateway/GatewayInterface.h, interfaces/sealer/SealerInterface.h, interfaces/storage/TableInterface.h, libcodec/abi/ContractABICodec.h, libcodec/abi/ContractABIType.cpp, libcodec/abi/ContractABIType.h, libcodec/scale/Common.h, libcodec/scale/Exceptions.h, libcodec/scale/ScaleDecoderStream.h, libcodec/scale/ScaleEncoderStream.h, libsealer/Common.h, libsealer/Sealer.cpp, libsealer/Sealer.h, libsealer/SealerConfig.h, libsealer/SealingManager.cpp, libsealer/SealingManager.h, libsync/interfaces/TxsSyncMsgFactory.h, libsync/interfaces/TxsSyncMsgInterface.h, libsync/protocol/PB/TxsSyncMsg.cpp, libsync/protocol/PB/TxsSyncMsg.h, libsync/protocol/PB/TxsSyncMsgFactoryImpl.h, libtable/Table.cpp, libtable/Table.h
=> add ../../ to path

testutils/SignatureImpl.h
add namespace for SignatureImpl.h
=> add namespace for SignatureImpl.h

interfaces/storage/StorageInterface.h, interfaces/storage/TableInterface.h, libtable/Table.cpp, libtable/Table.h, libtable/TableFactory.h, test/unittests/libtable/MemoryStorage.h, test/unittests/libtable/TableFactory.cpp
https://stackoverflow.com/questions/3310737/should-we-pass-a-shared-ptr-by-reference-or-by-value
=> add reference to shared_ptr

libsealer/SealerFactory.h
=> update path for SealerFactory

libprotocol/TransactionStatus.cpp, libprotocol/TransactionSubmitResultFactoryImpl.h, libtool/LedgerConfigFetcher.cpp, libtool/LedgerConfigFetcher.h
=> add ../ to serval path

CMakeLists.txt, libprotocol/protobuf/PBBlock.cpp, libprotocol/protobuf/PBBlock.h, libprotocol/protobuf/PBBlockFactory.h, libprotocol/protobuf/PBBlockHeader.cpp, libprotocol/protobuf/PBBlockHeader.h, libprotocol/protobuf/PBTransaction.cpp, libprotocol/protobuf/PBTransaction.h, libprotocol/protobuf/PBTransactionFactory.h, libprotocol/protobuf/PBTransactionReceipt.cpp, libprotocol/protobuf/PBTransactionReceipt.h, libsync/protocol/PB/TxsSyncMsg.h, libtool/Exceptions.h
remove include_directories SOURCE_DIR to avoid path mismatch
=> remove include_directories SOURCE_DIR to avoid path mismatch

interfaces/protocol/Block.h, libprotocol/protobuf/PBBlock.cpp, libprotocol/protobuf/PBBlock.h
remove useless nonces interface
=> remove useless nonces interface

interfaces/protocol/TransactionFactory.h, libprotocol/protobuf/PBTransactionFactory.h
=> add create tx with sign

interfaces/dispatcher/SchedulerInterface.h, interfaces/executor/ParallelExecutorInterface.h, interfaces/executor/ParallelManagerInterface.h, interfaces/protocol/ExecutionResult.h, interfaces/protocol/ProtocolTypeDef.h, interfaces/protocol/TransactionFactory.h, interfaces/protocol/TransactionSubmitResult.h, interfaces/protocol/TransactionSubmitResultFactory.h, libprotocol/TransactionSubmitResultFactoryImpl.h, libprotocol/TransactionSubmitResultImpl.h, libprotocol/protobuf/PBTransactionFactory.h, libutilities/Common.h, libutilities/Error.h, test/unittests/libprotocol/PBBlockTest.cpp
=> merge from dev

interfaces/executor/ContractStatus.h, interfaces/executor/ExecutionParams.h, interfaces/executor/ExecutionResult.h, interfaces/executor/ParallelTransactionExecutorInterface.h
=> add new files

interfaces/storage/StorageInterface.h, libtable/TableStorage.cpp, libtable/TableStorage.h
add import construct for TableStorage
=> add import construct for TableStorage

interfaces/storage/Common.h, interfaces/storage/StorageInterface.h, libtable/TableStorage.cpp, libtable/TableStorage.h, test/unittests/libtable/TestTableStorage.cpp
add const to storage interface
=> add const to storage interface

cmake/InstallInclude.cmake
add install libstorage headers
=> add install libstorage headers

interfaces/ledger/LedgerInterface.h, interfaces/storage/Common.h, interfaces/storage/Entry.h, interfaces/storage/StorageInterface.h, interfaces/storage/Table.h, libstorage/StateStorage.cpp, libstorage/StateStorage.h, libstorage/StorageInterface.cpp, libstorage/Table.cpp, libutilities/ConcurrentCOW.h, libutilities/Error.h, test/unittests/libtable/Table.cpp, test/unittests/libtable/TestStateStorage.cpp, test/unittests/libutilities/ConcurrentCOWTest.cpp, testutils/faker/FakeLedger.h
Change UPtr to UniquePtr, add some comment
=> Change UPtr to UniquePtr, add some comment

interfaces/executor/ExecutionResult.h
set setTo() in executionResult to pure virtual
=> set setTo() in executionResult to pure virtual

interfaces/storage/Entry.h, interfaces/storage/StorageInterface.h, interfaces/storage/Table.h, libstorage/StateStorage.cpp, libstorage/StateStorage.h, libstorage/StorageInterface.cpp, libstorage/Table.cpp, libutilities/BatchStorageHelper.h, libutilities/KVStorageHelper.h, test/unittests/faker/FakersTest.cpp, test/unittests/libtable/Entry.cpp, test/unittests/libtable/Table.cpp, test/unittests/libtable/TablePerf.cpp, test/unittests/libtable/TestStateStorage.cpp, test/unittests/libutilities/TestKVStorageHelper.cpp, testutils/faker/FakeDispatcher.h, testutils/faker/FakeKVStorage.h
=> update storage interfaces

interfaces/executor/ExecutionMessage.h, interfaces/storage/Common.h, interfaces/storage/StorageInterface.h
Add key_fields to s_tables, for precompiled
=> Add key_fields to s_tables, for precompiled

interfaces/multigroup/ChainInfo.h, interfaces/multigroup/ChainNodeInfo.h, interfaces/multigroup/ChainNodeInfoFactory.h, interfaces/multigroup/GroupInfo.h, interfaces/multigroup/GroupManagerInterface.h, interfaces/multigroup/GroupTypeDef.h, interfaces/multigroup/NodeInfo.h
rename nodeInfo to ChainNodeInfo
=> rename nodeInfo to ChainNodeInfo

interfaces/executor/ExecutionMessage.h, libstorage/StateStorage.cpp, libstorage/StateStorage.h, test/unittests/libtable/TestStateStorage.cpp
Add create flag for ExecutionMessage
=> Add create flag for ExecutionMessage

interfaces/storage/StorageInterface.h, libstorage/StateStorage.cpp, libstorage/StateStorage.h, test/unittests/libtable/TestStateStorage.cpp
=> Set storage to virtual child

.github/workflows/workflow.yml, interfaces/storage/Entry.h, libstorage/StateStorage.cpp, test/unittests/libtable/Entry.cpp, test/unittests/libtable/TestStateStorage.cpp
=> Add purge to statestorage

libtool/ConsensusNode.h, libutilities/ConcurrentCOW.h
Add consensusNode.h for ledger and executor
=> Add consensusNode.h for ledger and executor

interfaces/storage/StorageInterface.h, interfaces/storage/Table.h, libstorage/StateStorage.cpp, libstorage/StateStorage.h, libstorage/StorageInterface.cpp, libstorage/Table.cpp, test/unittests/libtable/TestStateStorage.cpp, test/unittests/libutilities/TestKVStorageHelper.cpp
Move tableInfo from Storage to Table
=> Move tableInfo from Storage to Table

interfaces/dispatcher/SchedulerInterface.h, interfaces/executor/ParallelTransactionExecutorInterface.h, interfaces/protocol/Block.h, libprotocol/protobuf/PBBlock.h, test/unittests/libprotocol/PBBlockTest.cpp, testutils/faker/FakeScheduler.h, testutils/protocol/FakeBlock.h
Support calcTransactionRoot by metadata
=> Support calcTransactionRoot by metadata

interfaces/protocol/Block.h
=> Use hash size

interfaces/protocol/Transaction.h, libstorage/StateStorage.cpp, test/unittests/libtable/TestStateStorage.cpp
Fix purge bug, add LIQUID_CREATE to Transaction
=> Fix purge bug, add LIQUID_CREATE to Transaction

interfaces/executor/ExecutionMessage.h
Add REVERT_KEY_LOCK for execution message
=> Add REVERT_KEY_LOCK for execution message

libstorage/StateStorage.cpp, libstorage/StateStorage.h, test/unittests/libtable/Entry.cpp
=> Comment storage log

interfaces/protocol/BlockHeader.h, interfaces/protocol/Transaction.h, interfaces/protocol/TransactionReceipt.h, libprotocol/protobuf/PBBlockHeader.cpp, libprotocol/protobuf/PBBlockHeader.h, libprotocol/protobuf/PBTransaction.cpp, libprotocol/protobuf/PBTransaction.h, libprotocol/protobuf/PBTransactionReceipt.h, testutils/protocol/FakeBlockHeader.h
Remove block header encode(bool) method
=> Remove block header encode(bool) method
